services:
  reverse-proxy:
    labels:
      # TODO: Change the host domain, as needed.
      - traefik.http.routers.rev-proxy.rule=Host(`proxy.example.com`)
      - traefik.http.routers.rev-proxy.tls.certresolver=LETSENCRYPTRESOLVER
      - traefik.http.routers.rev-proxy.middlewares=rev-proxy-auth
      - traefik.http.middlewares.rev-proxy-auth.basicauth.usersfile=/usr/src/.htpasswd
    volumes:
      # Basic Auth
      - ./.htpasswd:/usr/src/.htpasswd:ro
      # Let's Encrypt
      - ./acme.json:/usr/src/acme.json
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPTRESOLVER=true
      # TODO: Change this email, as needed.
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPTRESOLVER_ACME_EMAIL=john.doe@example.com
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPTRESOLVER_ACME_STORAGE=/usr/src/acme.json
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPTRESOLVER_ACME_HTTPCHALLENGE=true
      # used during the challenge
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPTRESOLVER_ACME_HTTPCHALLENGE_ENTRYPOINT=web
