services:
  reverse-proxy:
    labels:
      # TODO: Change the host domain, as needed.
      - traefik.http.routers.rev-proxy.rule=Host(`proxy.example.com`)
      - traefik.http.routers.rev-proxy.tls.certresolver=letsencryptresolver
      - traefik.http.routers.rev-proxy.middlewares=rev-proxy-auth
      - traefik.http.middlewares.rev-proxy-auth.basicauth.usersfile=/usr/src/.htpasswd
    volumes:
      # Basic Auth
      - ./.htpasswd:/usr/src/.htpasswd:ro
      # Let's Encrypt
      - ./letsencrypt:/letsencrypt
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencryptresolver=true
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencryptresolver_ACME_TLSCHALLENGE=false
      # TODO: Change this email, as needed.
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPTRESOLVER_ACME_EMAIL=john.doe@example.com
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencryptresolver_ACME_STORAGE=/letsencrypt/acme.json
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencryptresolver_ACME_DNSCHALLENGE=true
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencryptresolver_ACME_DNSCHALLENGE_PROVIDER=godaddy
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencryptresolver_ACME_DNSCHALLENGE_RESOLVERS=1.1.1.1,8.8.8.8
      - GODADDY_API_KEY_FILE=/run/secrets/godaddy_api_key
      - GODADDY_API_SECRET_FILE=/run/secrets/godaddy_api_secret
    secrets:
      - godaddy_api_key
      - godaddy_api_secret

secrets:
  godaddy_api_key:
    file: ./secrets/godaddy_api_key
  godaddy_api_secret:
    file: ./secrets/godaddy_api_secret
