services:
  reverse-proxy:
    container_name: traefik-reverse-proxy
    image: traefik:2.9
    labels:
      - traefik.enable=true
      - traefik.http.routers.rev-proxy.service=api@internal
      - traefik.http.routers.rev-proxy.entrypoints=web-secure
      - traefik.http.routers.rev-proxy.tls=true
    ports:
      # http
      - 80:80
      # https
      - 443:443
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Traefik static config file.
      - ./traefik.static.yaml:/etc/traefik/traefik.yaml:ro
    restart: unless-stopped
