api:
  # Enable dashboard.
  dashboard: true
  # Enable debug logs in container.
  debug: true
log:
  # Log and show everything.
  level: INFO
providers:
  # Run traefik with docker.
  docker:
    exposedByDefault: false
    watch: true
    # This is the default docker network from docker-compose.yaml file.
    # It's derived from container_name.
    # This network should be added as external network in other docker-compose.yaml files for other services.
    network: traefik-reverse-proxy_default
entryPoints:
  web:
    # Listen on http
    address: :80
    # Redirect http to https
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    # Listen on https
    address: :443
